---
- name: install Apache
  apt: pkg={{ item }} state=present
  with_items:
  - apache2
  - apache2-doc
  - apache2-utils
- name: Equivilent of apt-get update
  apt: update_cache=yes
- name: Equivilant of apt-get upgrade
  apt: upgrade=dist
